title: ancientrome.live
description: Roman language, culture, and history
url: https://ancientrome.live
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Blog
    url: /index.html
  - title: About
    url: /about
  - title: Lessons
    url: https://learn.ancientrome.live/
social:
  email: me@andrewg.me
